services:
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus

  alertmanager-webhook:
    image: mendhak/http-https-echo:31
    container_name: alertmanager-webhook
    ports:
      - "8085:8080"
